# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.2
language: objective-c
# cache: cocoapods
podfile: Example/Podfile
cache:
  yarn: true
  cocoapods: true
  directories:
    - node_modules
    - $HOME/Library/Caches/Homebrew
before_install:
- gem install cocoapods
- gem install xcpretty -N
- pod repo update
- pod install --project-directory=Example
- brew install yarn
- yarn install
- yarn run ganache-cli 
  --account="0x1636e10756e62baabddd4364010444205f1216bdb1644ff8f776f6e2982aa9f5,1000000000000000000" 
  --account="0x159b7c413354adec1bd31caaf7e4fde71e9132a5b29193d2f6181de777745493,1000000000000000000" 
  --account="0x4836d1e4785f62498ec6a7a61ff0d01e3fa97dba863a76f5a6c3ace47f62be3f,100000000000000000000" 
  --gasPrice="20000000000" --gasLimit="21000" --networkId="1" &
script:
- pod lib lint --allow-warnings
- set -o pipefail && xcodebuild clean test -enableCodeCoverage YES -workspace Example/Web3Swift.xcworkspace -scheme All-Tests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2' ONLY_ACTIVE_ARCH=NO | xcpretty
- bash <(curl -s https://codecov.io/bash) -t 475c7b5c-1657-4aa3-bd40-c699b20e518d